from django.contrib import admin
from fishdb.models import *

admin.site.register(CollectionMethods)
admin.site.register(Dissections)
admin.site.register(FishingHabitats)
admin.site.register(FishingMethods)
admin.site.register(FunctionalGroups)
admin.site.register(HHS)
admin.site.register(LengthWeights)
admin.site.register(Locations)
admin.site.register(MegaPhotoQuads)
admin.site.register(PackedSamples)
admin.site.register(Preprocessings)
admin.site.register(Results)
admin.site.register(SampleLocations)
admin.site.register(Samples)
admin.site.register(SampleTypes)
admin.site.register(SharkDissections)
admin.site.register(SharkPieces)
admin.site.register(SharkSamples)
admin.site.register(SharkStates)
admin.site.register(Sites)
admin.site.register(Species)
#admin.site.register(SpeciesHabitats)
#admin.site.register(SpeciesMethods)
admin.site.register(Specimens)
admin.site.register(SpecimenSpareSamples)
admin.site.register(Trays)
admin.site.register(Treatments)
admin.site.register(Waypoints)
